sales round-robin with location
tutorcruncher/hermes pull request #226
Opened 2024-05-10 09:18 UTC by PrenSJ2

in `choose-sales-person`﻿ we now get the location from the header

- also added sells gb, eu, us, au, row to Admin model

2024-05-10 11:24 UTC, PrenSJ2 commented
after this is merged then this should be aswell https://github.com/tutorcruncher/tutorcruncher.com/pull/2160

2024-05-21 09:38 UTC, DanJezeph15 reviewed
Ignore some of these comments if its fine, I'm not really sure the intended way for each thing to work.

* [ ] Error from earlier when no one set to sell anywhere.

```
File "/home/dan/repos/hermes/app/hermes/views.py", line 112, in choose_sales_person
    next_sales_person = admin_ids[0]
```

* [ ] You mentioned what happens if you go to choose-roundrobin with no plan and you get the following:
![image](https://github.com/tutorcruncher/hermes/assets/79392348/5931941b-e25c-4c0a-9a30-cab87887f85c)

* [ ] Does `cf_ipcountry` definitely work? If I print out what the value for it is, I always seem to get None. If it does work, any chance you can explain it to me.

* [ ] We should have a fallback for the following scenario:
Fionn set up to sell enterprise and nothing else, with sell_us, sell_gb, sell_row, etc all true
Sam setup to sell payg and startup but only in the uk
What happens if we have a payg coming in from the US. We'd have no one to take the call as Fionn doesn't sell that level and Sam who does is only setup for the UK

2024-05-21 10:25 UTC, PrenSJ2 commented
CF-IPCountry - is a request header appended by cloudflare, so we cant test it locally

to test live use a vpn

2024-05-21 13:28 UTC, DanJezeph15 requested changes

2024-05-21 13:28 UTC, DanJezeph15 commented on app/hermes/views.py
> +            next_sales_person = admins_ids[0]
This function is doing too much now imo and both parts use similar logic, I think for readability you should have a function called like `get_next_sales_person` and then it should take the admins and the latest_company if it exists. So it looks something like 

```python
if regional_admins:
    next_sales_person = _get_next_sales_person(regional_admins)
else:
    next_sales_person = _get_next_sales_person(admins)
```

and then the func could do something like:
```python
def _get_next_sales_person(admins, latest_company):
    if latest_company:
        <your try except code using the admins list passed through>
    else:
        <return like admins[0] or something>
```

Play around with the func tho and make sure it works as thats just pseudo code, then you can add a docstring and typehint so its easier to understand whats going on too.

2024-05-21 16:51 UTC, merged